name: Release

# Run workflow on tags
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.4.0

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Release Gradle Plugin
        run: |
          echo "" >> gradle.properties
          echo "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}" >> gradle.properties
          echo "gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" >> gradle.properties

          ./gradlew publishPlugins
